name: Go
on: [pull_request]
branches:
  - master
jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.25.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.25.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .
